# Generated by Django 3.1.4 on 2021-01-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profiel_pic',
            new_name='profile_pic',
        ),
    ]
